export const clientsMp = [{
        "id": 1,
        "name": "achelocal",
        "web": "https://app.achelocal.appmarketplace.com.br",
        "iosUser": "https://apps.apple.com/us/app/ache-local/id1504708811?l=pt&ls=1",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=com.br.achelocal",
        "androidProvider": null,
        "versionWeb": "2.23.1",
        "versionIosUser": "2.13.9",
        "versionIosProvider": null,
        "versionAndroidUser": "2.15.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "",
        "urlUploadAndroidUser": "",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": false,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-06T14:57:36.430Z"
    },
    {
        "id": 2,
        "name": "ajudaai",
        "web": "https://app.ajudaai.appmarketplace.com.br",
        "iosUser": "https://apps.apple.com/us/app/ajuda-ai/id1603669928",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.ajudaai",
        "androidProvider": null,
        "versionWeb": "2.26.2",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "aab",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/8568547146082455237/app/4972291228173367279/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-26T12:30:11.068Z"
    },
    {
        "id": 3,
        "name": "clickfood ",
        "web": "https://app.clickfood.appmarketplace.com.br/",
        "iosUser": "https://apps.apple.com/za/app/clickfood-delivery/id1522929218",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.clickfood&hl=pt",
        "androidProvider": null,
        "versionWeb": "2.23.1",
        "versionIosUser": "2.7.9",
        "versionIosProvider": null,
        "versionAndroidUser": "2.15.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "",
        "urlUploadAndroidUser": "",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": false,
        "createdAt": "2022-06-09T10:11:21.488Z",
        "updatedAt": "2022-06-14T17:01:51.190Z"
    },
    {
        "id": 4,
        "name": "demo",
        "web": "https://demo.appmarketplace.com.br",
        "iosUser": "https://apps.apple.com/us/app/marketplaceapp/id1534615121",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.codificar.fomefome",
        "androidProvider": null,
        "versionWeb": "2.26.2",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "apk",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5887817223763081215/app/4973745748397073837/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-26T12:30:05.883Z"
    },
    {
        "id": 5,
        "name": "dusha",
        "web": "https://app.dusha.appmarketplace.com.br/",
        "iosUser": "https://apps.apple.com/app/dusha/id1612306654",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.dusha",
        "androidProvider": null,
        "versionWeb": "2.26.2",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "apk",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5657606008065923757/app/4975692790965613060/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-06-09T10:11:21.488Z",
        "updatedAt": "2022-07-26T12:30:16.456Z"
    },
    {
        "id": 6,
        "name": "freefood",
        "web": "https://app.freefood.appmarketplace.com.br",
        "iosUser": "https://apps.apple.com/in/app/freefood/id1529160011",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.freefood",
        "androidProvider": null,
        "versionWeb": "2.23.1",
        "versionIosUser": "2.13.5",
        "versionIosProvider": null,
        "versionAndroidUser": "2.15.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "",
        "urlUploadAndroidUser": "",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": false,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-06-09T14:42:16.334Z"
    },
    {
        "id": 7,
        "name": "ichef",
        "web": "https://app.ichef.appmarketplace.com.br/",
        "iosUser": "https://apps.apple.com/app/id1523084163",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.ichefdelivery",
        "androidProvider": null,
        "versionWeb": "2.23.1",
        "versionIosUser": "-",
        "versionIosProvider": null,
        "versionAndroidUser": "1.7.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "",
        "urlUploadAndroidUser": "",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": false,
        "createdAt": "2022-06-15T17:41:16.037Z",
        "updatedAt": "2022-06-15T17:41:16.037Z"
    },
    {
        "id": 8,
        "name": "mariamariabox",
        "web": "https://app.mariamariabox.appmarketplace.com.br",
        "iosUser": "https://apps.apple.com/br/app/mariamariabox/id1604821083",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.mariamariabox",
        "androidProvider": null,
        "versionWeb": "2.27.0",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "aab",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5120700496387554154/app/4976421342033632290/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-26T12:30:17.435Z"
    },
    {
        "id": 9,
        "name": "medicol",
        "web": "https://app.medicol.appmarketplace.com.br",
        "iosUser": "https://apps.apple.com/br/app/medicol/id1574241148",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.medicolappmarketplace",
        "androidProvider": null,
        "versionWeb": "2.26.2",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "apk",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/6230927619511975906/app/4972469047594495433/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-26T12:30:17.798Z"
    },
    {
        "id": 10,
        "name": "molde",
        "web": "https://app.molde.appmarketplace.com.br",
        "iosUser": "https://apps.apple.com/us/app/molde/id1571195191",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.molde",
        "androidProvider": null,
        "versionWeb": "2.27.1",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "apk",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5887817223763081215/app/4972845076211451831/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-25T21:50:17.750Z"
    },
    {
        "id": 11,
        "name": "molde autopeças",
        "web": "https://molde.app.br/web/autopecas_1EsGCaFd/outlets.html?listing=show",
        "iosUser": "https://apps.apple.com/us/app/molde-autopecas/id1630824133",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.moldeautopecas",
        "androidProvider": null,
        "versionWeb": "2.27.1",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "aab",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5887817223763081215/app/4973798652868098174/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-07-12T19:45:30.568Z",
        "updatedAt": "2022-07-25T22:10:28.886Z"
    },
    {
        "id": 12,
        "name": "molde construção",
        "web": "https://molde.app.br/web/construcao_4IYHW2GF/outlets.html?listing=show",
        "iosUser": "https://apps.apple.com/us/app/molde-construcao/id1630824050",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.moldeconstrucao",
        "androidProvider": null,
        "versionWeb": "2.27.1",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "aab",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5887817223763081215/app/4976249541880903776/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-07-12T19:57:41.946Z",
        "updatedAt": "2022-07-25T22:10:32.298Z"
    },
    {
        "id": 13,
        "name": "molde farmácia",
        "web": "https://molde.app.br/web/farmacia_VS4eqNEB/outlets.html?listing=show",
        "iosUser": "https://apps.apple.com/us/app/molde-farm%C3%A1cia/id1631353668",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.moldefarmacia",
        "androidProvider": null,
        "versionWeb": "2.27.1",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "aab",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5887817223763081215/app/4973622282987548828/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-06-15T19:06:45.129Z",
        "updatedAt": "2022-07-25T22:10:32.490Z"
    },
    {
        "id": 14,
        "name": "molde pizzapoint",
        "web": "https://molde.app.br/web/pizza-point_gUrlhBXC/outlets.html?listing=show",
        "iosUser": "https://apps.apple.com/us/app/pizza-point-app/id1573640659",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.pizzapoint",
        "androidProvider": null,
        "versionWeb": "2.27.1",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "apk",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5887817223763081215/app/4973181177486856313/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-25T22:10:33.640Z"
    },
    {
        "id": 15,
        "name": "molde restaurante",
        "web": "https://molde.app.br/web/restaurante_2cQkrGT5/outlets.html?listing=show",
        "iosUser": "https://apps.apple.com/us/app/molde-restaurante/id1580823278",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.molde_restaurante",
        "androidProvider": null,
        "versionWeb": "2.27.1",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "aab",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5887817223763081215/app/4975455970587107307/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-07-12T22:42:09.272Z",
        "updatedAt": "2022-07-25T22:10:33.527Z"
    },
    {
        "id": 16,
        "name": "molde upfood",
        "web": "https://molde.app.br/web/upfood_4bbTTVPt/outlets.html?listing=show",
        "iosUser": "https://apps.apple.com/us/app/upfood-delivery/id1627531665",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.moldeupfood",
        "androidProvider": null,
        "versionWeb": "2.27.1",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "aab",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5887817223763081215/app/4976211597483929597/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-06-15T18:39:17.090Z",
        "updatedAt": "2022-07-25T22:10:33.871Z"
    },
    {
        "id": 17,
        "name": "pededetudo",
        "web": "https://app.pededetudo.appmarketplace.com.br/",
        "iosUser": "https://apps.apple.com/app/id1626001428",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.pededetudo",
        "androidProvider": null,
        "versionWeb": "2.26.2",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "aab",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/5887817223763081215/app/4973126392195638670/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-26T12:30:14.618Z"
    },
    {
        "id": 18,
        "name": "pedeme",
        "web": "https://app.pedeme.appmarketplace.com.br/",
        "iosUser": "https://apps.apple.com/us/app/pede-me/id1634787954",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.pedeme",
        "androidProvider": null,
        "versionWeb": "2.26.2",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "aab",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/7962309792984069027/app/4973771651994423755/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-06-15T17:35:33.421Z",
        "updatedAt": "2022-07-26T12:30:15.407Z"
    },
    {
        "id": 19,
        "name": "pedenobairro",
        "web": "https://app.pedenobairro.appmarketplace.com.br",
        "iosUser": "https://apps.apple.com/br/app/pede-no-bairro/id1527831739",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.pedenobairro",
        "androidProvider": null,
        "versionWeb": "2.26.2",
        "versionIosUser": "2.16.0",
        "versionIosProvider": null,
        "versionAndroidUser": "2.16.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "apk",
        "urlUploadAndroidUser": "https://play.google.com/console/u/0/developers/9025655114453760810/app/4973109547809427768/tracks/production",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": true,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-26T12:30:16.805Z"
    },
    {
        "id": 20,
        "name": "pidao",
        "web": "https://app.pidao.appmarketplace.com.br",
        "iosUser": "https://apps.apple.com/br/app/pid%C3%A3o/id1534631942",
        "iosProvider": null,
        "androidUser": "https://play.google.com/store/apps/details?id=br.com.codificar.pidao",
        "androidProvider": null,
        "versionWeb": "2.23.1",
        "versionIosUser": "2.11.2",
        "versionIosProvider": null,
        "versionAndroidUser": "2.15.0",
        "versionAndroidProvider": null,
        "extensionAndroid": "",
        "urlUploadAndroidUser": "",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": false,
        "createdAt": "2022-05-31T17:53:34.167Z",
        "updatedAt": "2022-07-07T21:36:56.412Z"
    },
    {
        "id": 21,
        "name": "transf",
        "web": "https://app.transfdelivery.appmarketplace.com.br/",
        "iosUser": "-",
        "iosProvider": null,
        "androidUser": "-",
        "androidProvider": null,
        "versionWeb": "2.23.1",
        "versionIosUser": "-",
        "versionIosProvider": null,
        "versionAndroidUser": "-",
        "versionAndroidProvider": null,
        "extensionAndroid": "",
        "urlUploadAndroidUser": "",
        "urlUploadAndroidProvider": null,
        "projectId": 1,
        "status": false,
        "createdAt": "2022-06-14T18:23:08.126Z",
        "updatedAt": "2022-06-15T17:41:56.503Z"
    }
];